products = [
{
      '_id': '1',
      'name': 'Sony Cybershot DSC-S730',
      'image': '/images/SonyCybershot.jpg',
      'brand': 'Sony',
      'category': 'Digital Camera',
      'description': 'Compact digital camera with 7.2 megapixels and 3x optical zoom.',
      'price': 1100,
      'countInStock': 0,
      'rating': 4.5,
      'numReviews': 12,
    },

{
      '_id': '2',
      'name': 'Canon Powershot A1100 IS',
      'image': '/images/CanonPowershot.jpg',
      'brand': 'Canon',
      'category': 'Digital Camera',
      'description': '10.0 megapixels with 4x optical zoom and image stabilization.',
      'price': 1200,
      'countInStock': 7,
      'rating': 4.0,
      'numReviews': 8,
    },
{
      '_id': '3',
      'name': 'Nikon Coolpix L22',
      'image': '/images/NikonCoolpix.jpg',
      'brand': 'Nikon',
      'category': 'Digital Camera',
      'description': '12.1 megapixels with 3x optical zoom and easy-to-use features.',
      'price': 1500,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
{
      '_id': '4',
      'name': 'Samsung ES15',
      'image': '/images/Samsung.jpg',
      'brand': 'Samsung',
      'category': 'Digital Camera',
      'description': '14.2 megapixels with 5x optical zoom and smile detection technology.',
      'price': 1000,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
{
      '_id': '5',
      'name': 'Fujifilm FinePix A400',
      'image': '/images/Fujifilm.jpg',
      'brand': 'Fujifilm',
      'category': 'Digital Camera',
      'description': '16.0 megapixels with 5x optical zoom and easy auto mode.',
      'price': 1800,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
{
      '_id': '6',
      'name': 'Kodak EasyShare C183',
      'image': '/images/Kodak.jpg',
      'brand': 'Kodak',
      'category': 'Digital Camera',
      'description': '18.0 megapixels with 3x optical zoom and 2.7-inch LCD screen.',
      'price': 1250,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
]